name: Compiler Vuepress
on:
  push:
    branches:
      - main
jobs:
  compileVuepress:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run docs:build
      - run: git fetch
      - run: git add .
      - run: git stash #Guardar auxiliarmente los cambioss
      - run: git checkout gh-pages
      #- run: rm -r docs #Borrar carpeta mydocs
      - run: git stash apply #setear los cambios anteiores
    #  - run: rm -r mydocs #Borrar carpeta mydocs
    #  - run: mv dest mydocs  #Rename dest to mydocs
      - run: git add .
      - run: git config --global user.email "gustavocondezocamayo@gmail.com"
      - run: git config --global user.name "Gustavo Condezo"
      - run: git commit -m "update docs"
      - run: git push origin gh-pages --force
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository codes
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
